### ISSUE TITLE
Access denied on service registration

### ISSUE THREAD

**Issue by jbcr** [InExtenso/win32service#71]
When I use the Win32ServiceBundle, I have this error from Win32Extension:

Configuration:
```
win32_service:
  windows_local_encoding: ISO-8859-1
  services:
    - service_id: "runner"
      displayed_name: "runner"
      recovery:
        enable: true # The recovery action is disabled
        delay: 60000 # The delay before run action (in millisecond)
        action1: 2 # The action for the first fail
        action2: 2 # The action for the second fail
        action3: 2 # The action for the next fail
        reset_period: 5 # The period before reset the fail count (in minutes)
      dependencies: # The list of service depends
        - Netman # An example of dependency.

```

Result

```
>php81 bin\console win32service:register -vvv
^ Win32ServiceException {#160
  #message: "Error access denied"
  #code: 5
  #file: "C:\Sites\wwwroot\runner\vendor\win32service\service-library\lib\Service\ServiceAdminManager.php"
  #line: 48
  trace: {
    C:\Sites\wwwroot\runner\vendor\win32service\service-library\lib\Service\ServiceAdminManager.php:48 { …}
    C:\Sites\wwwroot\runner\vendor\win32service\win32servicebundle\lib\Command\RegisterServiceCommand.php:115 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\console\Command\Command.php:308 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\console\Application.php:1020 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\framework-bundle\Console\Application.php:94 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\console\Application.php:299 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\framework-bundle\Console\Application.php:80 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\console\Application.php:171 { …}
    C:\Sites\wwwroot\runner\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:54 { …}
    C:\Sites\wwwroot\runner\vendor\autoload_runtime.php:29 { …}
    C:\Sites\wwwroot\runner\bin\console:11 {
      ›
      › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
      ›
      arguments: {
        "C:\Sites\wwwroot\runner\vendor\autoload_runtime.php"
      }
    }
  }
}
 Error : inference_runner(5) Access to service inference_runner is denied
1 service(s) processed
```

![image](https://user-images.githubusercontent.com/51637606/189133735-b1659f34-71e9-46fa-a928-c903481df459.png)
